### ISSUE TITLE
what plugins are going to be supported or is it going to have its own plugins and when is it going to be released 

### ISSUE THREAD

**Issue by Cxsmo-ai** [WorriedArrow/OpenLoader#1]
what plugins are going to be supported or is it going to have its own plugins and when is it going to be released

**Comment by WorriedArrow** [comment]
I should hopefully have a working alpha out this weekend. It's going to have its own plugins, and I do not plan on supporting any other plugin APIs. However, the structure of the loader should allow for people to create plugins for making other plugins compatible, essentially creating wrapper functions/classes with the same name as the other API.
