### ISSUE TITLE
When is it coming out

### ISSUE THREAD

**Issue by Cxsmo-ai** [WorriedArrow/OpenLoader#2]
When is it coming out

**Comment by WorriedArrow** [comment]
It'll likely come out tomorrow as long as I can get everything ironed out and compatible.

Note that I'm not sure when the installer will come out, so for now, you'll have to manually build it. I will have the build script in the repository though.

**Comment by Cxsmo-ai** [comment]
okay and is there plugins that are coming out with it or i have to wait for other people to make them

**Comment by WorriedArrow** [comment]
I'll likely create a few utility plugins for it. Other people, however, can certainly make them!
I might make a repository with my plugins where you can make issues to request plugins.

**Comment by Cxsmo-ai** [comment]
The main plugin that would be cool to have on openloader would be https://github.com/riolubruh/YABDP4Nitro because this guy plugin is insane and he's also eventually adding custom discord actitives and stuff to it like super Mario 64 built into a discord activity all in that one plugin

**Comment by WorriedArrow** [comment]
Wow, that looks neat.
Most of the features would be 100% plausible to add in an official OpenLoader plugin!
Great suggestion! Many of these features will definitely be high on my priority list for officially supported plugins.
