### ISSUE TITLE
Where are plugins for this and is there a easy way to convert better discord plugins to openloader

### ISSUE THREAD

**Issue by Cxsmo-ai** [WorriedArrow/OpenLoader#9]
Where are plugins for this and is there a easy way to convert better discord plugins to openloader

**Comment by WorriedArrow** [comment]
I'm currently working on a few plugins.
Unfortunately, there is not an easy way to convert BetterDiscord plugins to work with OpenLoader, unless they do not use any BetterDiscord-specific code, which is quite rare.

One thing to note, though, is that the structure of the loader *should* allow someone to create a plugin that creates "wrappers" for OpenLoader code using the BetterDiscord names, however I cannot guarantee that that will happen.
